- Gemfile.lock
- README.md
- freddy.gemspec
- lib/freddy.rb
- lib/freddy/consumer.rb
- spec/integration/concurrency_spec.rb
Happens when calling deliver_with_response inside a respond_to or
tap_into block.
> Fix a deadlocking issue

- Gemfile.lock
- README.md
- freddy.gemspec
- lib/freddy.rb
- lib/freddy/consumer.rb
- lib/freddy/request.rb
- spec/integration/concurrency_spec.rb
Creating new threads forces all thread-local state to be reinitialized.
This means creating new PG connections and AR pools and so on.
Moreover, some requests timing out can lead to an explosion
of parallelism which creates very many threads and as a result of this
also very many file handlers for amqp pipes and user connections (e.g PG).
Therefore it is necessary to bound parallelism while still allowing
unlimited reqres inside a responder.
This can be done by listening for RPC responses on a dedicated thread
and moving consumer threads into a thread pool.
> Fix unbounded parallelism

- lib/freddy/consumer.rb
Helps to trace requests that time out or result in errors
> Add correlation id to freddy logs

- Gemfile.lock
- freddy.gemspec
- lib/freddy/request.rb
- lib/freddy/request_manager.rb
Helps to better classify the errors by name.
> Avoid making error messages unique when notifying error reporter

- freddy.gemspec
- lib/freddy/sync_response_container.rb
- spec/freddy/sync_response_container_spec.rb
Performance test [deliver_with_response 10K messages] on my local computer:
**before**: `4.920000   2.360000   7.280000 (  6.821925)`
**after**: `4.330000   1.520000   5.850000 (  5.137929)`
> Replace sleep with proper wakeup mechanism

- README.md
Was pointing to node-freddy build instead.
> Fix Travis badge in README

- freddy.gemspec
- lib/freddy/payload.rb
This is so that strings will stay strings when loaded instead of strings
starting with ':' (a colon) being automatically converted into symbols.
> Configure oj to use strict mode

- lib/freddy/producers/send_and_wait_response_producer.rb
- lib/freddy/sync_response_container.rb
- spec/freddy/sync_response_container_spec.rb
If the response is already received then just returned it. There's no
reason to wait for resource signal.
> Fix race condition in wait_for_response

- lib/freddy.rb
- lib/freddy/consumers/tap_into_consumer.rb
- spec/integration/tap_into_with_group_spec.rb
- spec/spec_helper.rb
This allows only one of the `tap_into` listeners in a group to receive a
message.
> Add `group` option to Freddy#tap_into

- README.md
- freddy.gemspec
- lib/freddy.rb
- lib/freddy/adapters.rb
- lib/freddy/adapters/bunny_adapter.rb
- lib/freddy/adapters/march_hare_adapter.rb
- lib/freddy/consumers/respond_to_consumer.rb
- lib/freddy/consumers/response_consumer.rb
- lib/freddy/consumers/tap_into_consumer.rb
- lib/freddy/delivery.rb
- lib/freddy/producers/send_and_wait_response_producer.rb
- spec/freddy/consumers/respond_to_consumer_spec.rb
- spec/freddy/responder_handler_spec.rb
Previously we were taking all messages using Queue#subscribe and then
using a thread pool to process them. It is more useful to keep the
messages that cannot be processed yet in the queue. This allows adding
new consumers that can start processing them.
Prefetch value tells rabbitmq how many messages can consumers on a
channel be given at a time (before they have to acknowledge or reject
one of the earlier received messages).
> Avoid consuming messages before being able to process them

- freddy.gemspec
- lib/freddy.rb
- spec/spec_helper.rb
Previously tests required it themselves and the library expected it is already required by the client app. This is not always the case. Making it explicitly required.
> Require securerandom in main freddy file

- freddy.gemspec
- lib/freddy/payload.rb
- spec/freddy/payload_spec.rb
json lib serializes time objects as:
```
2.4.0 :007 > puts JSON.dump(x: Time.now)
{"x":"2017-01-30 13:43:21 +0200"}
```
Oj with compat mode serializes it as:
```
puts Oj.dump({x: Time.now}, mode: :compat)
{"x":1485776878.255169415e7200}
```
Neither of them are good to send over wire. Use iso8601 format
instead.
Changing mri ruby was done by adding `time_format: :xmlschema` to Oj.
Changing jruby was more complicated because its json lib does not
support time format flags.
> Serialize time objects

- freddy.gemspec
- lib/freddy/payload.rb
Precision 6 has been chosen because PostgreSQL also stores timestamps with
6 digits after point. This should fix issues with serialization of ActiveRecord
timestamp attributes.
> Limit timestamps precision when serializing objects with Oj

- Gemfile
- freddy.gemspec
- lib/freddy/delivery.rb
- lib/freddy/trace_carrier.rb
- spec/integration/logging_spec.rb
- spec/integration/tracing_spec.rb
This is not freddy job. The tracer client must take care of it.
> Remove has_required_fields? from TraceCarrier

- freddy.gemspec
- lib/freddy/payload.rb
Oj changelog: https://github.com/ohler55/oj/blob/master/CHANGELOG.md
The previous version didn't work with ruby 2.5. It does not seem that v2
will be changed to support it. v3 however supports ruby 2.5 just fine.
> Upgrade oj to ~> 3.6

- lib/freddy.rb
- lib/freddy/adapters/bunny_adapter.rb
- lib/freddy/adapters/march_hare_adapter.rb
- lib/freddy/consumers/tap_into_consumer.rb
- spec/integration/tap_into_with_group_spec.rb
Also, allow requeueing faulty messages in #tap_into.
These two features may be useful to create reliable consumers (e.g. faulty message can be requeued on exception, queues can survive server crash).
> Allow specifying durable queues for #tap_into

- freddy.gemspec
- spec/freddy/payload_spec.rb
The license listed on RubyGems.org is "private", and we didn't link to the GitHub repo.
> Update license and add homepage

- lib/freddy/delivery.rb
- lib/freddy/version.rb
- spec/integration/tracing_spec.rb
RPC still uses the same trace, but broadcasts (Freddy#deliver) now create
new traces but we still store the original trace link for observability.
I previously went against the spec because Zipkin doesn't support links. 
But we're likely going to replace Zipkin and it's better to follow the 
OpenTelemetry spec.
> Start a new trace when receiving a broadcast

- lib/freddy/adapters/bunny_adapter.rb
- lib/freddy/version.rb
This is usually present because some other gem loads it as well. In one of
our microservices however no other depdenecy required it. Requiring freddy
failed with:
```
uninitialized constant Freddy::Adapters::BunnyAdapter::Channel::Forwardable
```
> Explicitly require forwardable

- lib/freddy/delivery.rb
- lib/freddy/version.rb
- spec/integration/tracing_spec.rb
- spec/spec_helper.rb
Receiving a broadcast had a bug. It created a root span and then used
`in_span` which creates a new span with same content, causing a duplicate
span.
> Do not create duplicate spans

- lib/freddy/producers/reply_producer.rb
- lib/freddy/producers/send_and_forget_producer.rb
- lib/freddy/producers/send_and_wait_response_producer.rb
- lib/freddy/tracing.rb
- lib/freddy/version.rb
- spec/integration/tracing_spec.rb
`span_for_produce` method creates a new span using `start_span` call. This
method doesn't automatically change the OpenTelemetry current context like
`in_span` and `with_span`. This meant that the
`propagation.inject` used a wrong span. The traces still included all the
spans but the ordering was incorrect because the receiver spans had wrong
parent spans.
> Fix propagating span ID

- .github/workflows/ci.yml
- .gitignore
- Gemfile.lock
- lib/freddy/consumers/tap_into_consumer.rb
- lib/freddy/delivery.rb
- lib/freddy/version.rb
- spec/integration/tracing_spec.rb
I initially used [Link][1] relationship for `Freddy#tap_into`. But many
vendors (including the one we use) don't really support it. After
re-reading the documentation and also looking [an example][2] it seems that
using Parent-Child relationship makes more sense here.
Some libraries also provide an option `propagation_style` to switch between
the two. In this case I don't think we need/should do that.
[1]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#links-between-spans
[2]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#topic-with-multiple-consumers
> Change tap_into span relationship to parent-child

- Gemfile
- Gemfile.lock
- freddy.gemspec
- lib/freddy.rb
- lib/freddy/consumers/respond_to_consumer.rb
- lib/freddy/consumers/tap_into_consumer.rb
- lib/freddy/responder_handler.rb
- lib/freddy/version.rb
- spec/freddy/consumers/respond_to_consumer_spec.rb
- spec/freddy/sync_response_container_spec.rb
- spec/integration/tracing_spec.rb
- spec/spec_helper.rb
This gem depends on depends on gem [thread](https://rubygems.org/gems/thread/versions/0.2.2) which is licensed under WTFPL license. 
That gem is not actively maintained and all of its functionality is included into a well-known gem [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby), which is distributed under MIT license.
Deleting Gemfile.lock, because as it is ignored when installing the gem, the presense of Gemfile.lock is more likely to hide issues with incompatibility with newer versions of dependencies that applications might use.
> Replace thread gem with concurrent-ruby gem

- .rubocop.yml
- freddy.gemspec
Removing MFA requirement for gem publishing and corresponding RuboCop rule to allow auto-publish with GitHub action.
> Disable MFA requirement in gemspec

- Gemfile
- Gemfile.lock
- freddy.gemspec
- lib/freddy/version.rb
To allow other projects to use newer `opentelemetry-api` version, this
commit loosens the version from `1.0.0rc3` and allows to use any `1.x`
version.
[Changelog][1] doesn't contain any breaking changes.
[1]: https://open-telemetry.github.io/opentelemetry-ruby/opentelemetry-api/v1.1.0/file.CHANGELOG.html
> Loosen opentelemetry-sdk gem version

- Gemfile.lock
- lib/freddy.rb
- lib/freddy/consumers/respond_to_consumer.rb
- lib/freddy/consumers/tap_into_consumer.rb
- lib/freddy/version.rb
- spec/freddy/freddy_spec.rb
- spec/freddy/responder_handler_spec.rb
- spec/integration/concurrency_spec.rb
- spec/integration/reply_spec.rb
- spec/integration/tap_into_with_group_spec.rb
- spec/integration/tracing_spec.rb
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
> In Ruby 3.0, positional arguments and keyword arguments will be separated.
> Ruby 2.7 will warn for behaviors that will change in Ruby 3.0.
> Handle keyword argument warnings

- lib/freddy.rb
- lib/freddy/consumers/tap_into_consumer.rb
- lib/freddy/delivery.rb
- spec/integration/tap_into_with_exchange_spec.rb
* Make exchange name configurable for tap_into listener.
> The messages can only be heard from the `freddy-topic` exchange.
> This commit makes the it possible to listen to messages from different exchange
> by defining `exchange_name` option's parameter.'
* Make delivery timestamp available for tap into the consumer.
> The timestamp is necessary for some applications that need an event start time.
> It defaults to nil if the message timestamp doesn't exit.
> Make exchange name configurable for tap into consumer

- .github/workflows/publish.yml
This change is done because the old one was deprecated had wouldn't publish new releases anymore
> Update the publishing process of ruby gems

- Gemfile.lock
- README.md
- lib/freddy.rb
- lib/freddy/version.rb
- spec/freddy/freddy_spec.rb
Headers are the main point for including message metadata in AMQP.
Headers are already in use to propagate traces.
Allow library users to add arbitrary headers themselves.
> Support custom headers
